version: '2'

services:
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=dockerphpipam
    restart: always
    volumes:
      - db_data:/var/lib/mysql
  ipam:
    depends_on:
      - mysql
    restart: always
    image: pierrecdn/phpipam
    environment:
      - MYSQL_ENV_MYSQL_USER=user
      - MYSQL_PASSWORD=dockerphpipam
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=dockerphpipam
      - MYSQL_ENV_MYSQL_HOST=mysql
    ports:
      - "80:80"
volumes:
  db_data:

#docker-compose up -d
